import React, { useState } from "react";
import { motion } from "framer-motion";
import styles from "./Research.module.scss";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import SideBar from "../../components/SideBar";
import { useMediaQuery } from "@mui/material";
import FloatingBackButton from "../../components/FloatingBackButton";
const Background2 = dynamic(() => import("../../components/Background2"), {
  ssr: false,
});
interface ItemType {
  id: number;
  title: string;
  list: string[];
}
const Backdrop = ({
  children,
  onClick,
}: {
  children: JSX.Element;
  onClick: React.MouseEventHandler<HTMLButtonElement>;
}) => {
  return (
    <div className={styles.container} >
      <motion.div
        className={styles.backDrop}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 1 }}
      >
        <div className={styles.backDropContainer}>
          <div className={styles.backDropChildren}>{children}</div>
        </div>
      </motion.div>
    </div>
  );
};
const items: ItemType[] = [
  {
    id: 1,
    title: "Objectives",
    list: [
      "1. To create Centers of Excellence in emerging areas and to sustain Research through innovation.",
      "2. To encourage the students and members of the faculty to involve in inter-disciplinary and multi-disciplinary research.",
      "3. To realize sustainable development goals and in the process, find solutions for societal problems.",
    ],
  },
  {
    id: 2,
    title: "Provisions",
    list: [
      "1. An office for Research will be created under the leadership of Dean (Research) to track and coordinates all activities related to research and innovation in the departments and that of the institution.",
      "2. Sufficient budget for Research will be created separately under Capital and Revenue heads. Whenever essential, additional grants can be considered with proper justification.",
    ],
  },
  {
    id: 3,
    title: "Process",
    list: [
      "1. National/International travel grant to faculty and students to enable them to participate and present research papers in Conferences.",
      "2. Sponsorship to attend conferences, workshops and all Professional Development Programmes.",
      "3. Grant for Under-graduate and Post-graduate students will be provided to support innovative final year projects.",
      "4. Seed money will be provided to carry out research projects for members of the faculty.",
      "5. Incentives will be offered for paper publications based on the quality of publications at the end of each year.",
      "6. Performance Based Incentives will be offered to faculty members based on various activities pertaining to Research and Innovation like consultancy, testing, patents, etc. based on guidelines issued from time to time.",
      "7. Incentives for successful completion of Funded Projects will be given to Principal Investigators as per guidelines and the same paid at the end of every year.",
      "8. Financial support to avail Life Membership in Professional Societies will be provided.",
      "9. Sabbatical leave will be provided to faculty to pursue PhD/PDF.",
    ],
  },
];
const List = ({ item }: { item: ItemType }) => {
  const [expanded, setExpanded] = useState(false);
  return (
    <motion.div
      layout="position"
      onClick={() => setExpanded(!expanded)}
      className={styles.listContainer}
    >
      <div>{item.title}</div>
      {expanded && (
        <Backdrop onClick={() => setExpanded(!expanded)}>
          <div className={styles.pointsContainer}>
            <div>{item.title}</div>
            {item.list.map((points, i) => {
              return <div key={i}>{points}</div>;
            })}
          </div>
        </Backdrop>
      )}
    </motion.div>
  );
};
const Research = () => {
  const showSideBar = useMediaQuery("(max-width:600px)");
  return (
    <div>
      <div className={styles.bg}>
        <Background2 />
      </div>
      <div className={styles.container}>
        <Head>
          <title>Sri Venkateswara College of Engineering</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.sideBar}>
          <SideBar />
        </div>
        {!showSideBar && <div className={styles.emptyForAReason}></div>}
        <div className={styles.innerContainer}>
          <div className={styles.logoContainer}>
            {showSideBar && <div className={styles.emptyForAReason}></div>}
            <Image
              className={styles.logo}
              src="/images/svce.png"
              alt="SVCE"
              width={150}
              height={30}
            />
          </div>
          <div className={styles.research}>
            {/* <motion.div
              layout="position"
              className={styles.box}
              data-expanded={expanded}
              onClick={() => setExpanded(!expanded)}
            /> */}
            <div className={styles.statement}>
              <div>Statement</div>
              <div>
                To build a strong Research and Innovation Ecosystem to improve
                the quality of Research and Innovation in the institution in
                line with the Vision and Mission of the institution.
              </div>
            </div>
            <div className={styles.list}>
              {items.map((item, i) => {
                return (
                  <div key={i} className={styles.listItems}>
                    <List item={item} />
                  </div>
                );
              })}
            </div>
          </div>
        </div>
        <div className={styles.floatingButton}>
          <FloatingBackButton />
        </div>
      </div>
    </div>
  );
};

export default Research;
